name: glucose_project
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - flask
  - flask-cors
  - pandas
  - scikit-learn
  - statsmodels
  - matplotlib
  - numpy
  - sympy
  - networkx
  - jinja2
  - pyyaml
  - requests
  - httpx
  - pysocks
  - beautifulsoup4
  - jupyterlab
  - ipywidgets
  - pip:
      - camelot-py==1.0.9
      - google-generativeai
      - pydantic
      - huggingface-hub==0.36.0
      - openai
      - opencv-python-headless==4.12.0.88
      - pdfminer-six==20250506
      - pdfplumber==0.11.7
